services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - kbmnet
    volumes:
      - sql_data:/var/opt/mssql
      - ./sql:/docker-entrypoint-initdb.d/
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/entrypoint.sh"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    
  kbmgrpcservice:
    build:
      context: ../
      dockerfile: KBMGrpcService/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: kbmgrpcservice
    ports:
      - "5001:5001"
    depends_on:
      - sqlserver
    networks:
      - kbmnet
    environment:
      - DB_HOST=sqlserver
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

  kbmhttpservice:
    build:
      context: ../
      dockerfile: KBMHttpService/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: kbmhttpservice
    ports:
      - "5000:5000"
    depends_on:
      - kbmgrpcservice
    networks:
      - kbmnet
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - debuggerdata:/tmp/debugger
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

networks:
  kbmnet:
    driver: bridge

volumes:
  sql_data: